# Generated by Django 5.1 on 2024-10-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Science', 'Science')], max_length=255)),
                ('description', models.TextField()),
                ('prerequisites', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(max_length=50)),
                ('answer_type', models.CharField(max_length=50)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_project.assignment')),
            ],
        ),
    ]
