# Generated by Django 5.1.1 on 2024-10-16 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Mathematics', 'Mathematics'), ('Science', 'Science')], max_length=50)),
                ('description', models.TextField()),
                ('prerequisites', models.TextField(blank=True)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('descriptive', 'Descriptive')], max_length=20)),
                ('correct_choice', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_project.assignment')),
            ],
        ),
    ]
