# Generated by Django 5.1.1 on 2024-10-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_project', '0002_assignment_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Answers')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('text', 'Text Input'), ('upload', 'File Upload')], max_length=20),
        ),
    ]
