# Generated by Django 5.1.1 on 2024-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_project', '0003_remove_question_correct_choice_question_answer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
