# Generated by Django 5.1.1 on 2024-10-15 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 11, 19, 5, 156102, tzinfo=datetime.timezone.utc)),
        ),
    ]
